Importing the Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")

Exporatory Data Analysis

In [2]:
from sklearn.datasets import load_digits
digits=load_digits()

In [4]:
digits["data"]

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64))

In [5]:
digits["target"]

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

In [6]:
digits["feature_names"]

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [7]:
df_data=pd.DataFrame(digits["data"],columns=digits["feature_names"])

In [8]:
df_data.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [10]:
df_data.shape

(1797, 64)

Preparing for PCA

In [11]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler= StandardScaler()
scaled_data=scaler.fit_transform(df_data)#Needs to be converted ino a dataframe structure

In [15]:
df_new=pd.DataFrame(scaled_data,columns=digits["feature_names"])

In [16]:
df_new.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,-0.335016,-0.043081,0.274072,-0.664478,-0.844129,-0.409724,-0.125023,-0.059078,-0.624009,...,-0.757436,-0.209785,-0.023596,-0.299081,0.086719,0.208293,-0.366771,-1.146647,-0.505670,-0.196008
1,0.0,-0.335016,-1.094937,0.038648,0.268751,-0.138020,-0.409724,-0.125023,-0.059078,-0.624009,...,-0.757436,-0.209785,-0.023596,-0.299081,-1.089383,-0.249010,0.849632,0.548561,-0.505670,-0.196008
2,0.0,-0.335016,-1.094937,-1.844742,0.735366,1.097673,-0.409724,-0.125023,-0.059078,-0.624009,...,0.259230,-0.209785,-0.023596,-0.299081,-1.089383,-2.078218,-0.164037,1.565686,1.695137,-0.196008
3,0.0,-0.335016,0.377661,0.744919,0.268751,-0.844129,-0.409724,-0.125023,-0.059078,1.879691,...,1.072563,-0.209785,-0.023596,-0.299081,0.282736,0.208293,0.241430,0.379040,-0.505670,-0.196008
4,0.0,-0.335016,-1.094937,-2.551014,-0.197863,-1.020657,-0.409724,-0.125023,-0.059078,-0.624009,...,-0.757436,-0.209785,-0.023596,-0.299081,-1.089383,-2.306869,0.849632,-0.468564,-0.505670,-0.196008

PCA with two Components

In [18]:
from sklearn.decomposition import PCA

In [19]:
pca= PCA(n_components=2)#we need two components so n_components=2

In [20]:
df_pca=pca.fit_transform(df_new)

In [21]:
df_pca.shape

(1797, 2)

In [22]:
component_df=pd.DataFrame(data=df_pca,columns=["first component","second component"])

In [23]:
component_df

      first component  second component
0           -1.914214         -0.954502
1           -0.588980          0.924636
2           -1.302039         -0.317189
3            3.020770         -0.868772
4           -4.528949         -1.093480
...               ...               ...
1792        -0.104331          0.255024
1793        -2.423234         -1.429611
1794        -1.022596         -0.147911
1795        -1.076055         -0.380906
1796         1.257702         -2.227591

[1797 rows x 2 columns]

In [ ]:
pca.explained_variance_

array([7.34477606, 5.83549054])

In [25]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054])

In [26]:
np.cumsum(pca.explained_variance_ratio_)

array([0.12033916, 0.21594971])

PCA with four components

In [27]:
pca= PCA(n_components=4)

In [28]:
df_pca=pca.fit_transform(df_new)

In [29]:
component_df=pd.DataFrame(data=df_pca,columns=["first component","second component","third component","fourth component"])

In [30]:
component_df

      first component  second component  third component  fourth component
0           -1.914214         -0.954502        -3.946035         -2.028723
1           -0.588980          0.924636         3.924755          1.779850
2           -1.302039         -0.317189         3.023333          2.043376
3            3.020770         -0.868772        -0.801744          2.187039
4           -4.528949         -1.093480         0.973121          1.419510
...               ...               ...              ...               ...
1792        -0.104331          0.255024        -3.765861          1.947006
1793        -2.423234         -1.429611        -3.045245         -2.632089
1794        -1.022596         -0.147911         2.469974          0.620307
1795        -1.076055         -0.380906        -2.455487          1.312013
1796         1.257702         -2.227591         0.283628          0.127073

[1797 rows x 4 columns]

In [36]:
pca.explained_variance_

array([7.34477606, 5.83549054, 5.15396118, 3.96623597])

In [37]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408])

In [38]:
np.cumsum(pca.explained_variance_ratio_)

array([0.12033916, 0.21594971, 0.30039385, 0.36537793])