Importing the Libraries and the Dataset

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Learning\Week-01(Python & OOP)\Learning-Curve\Week-4\Day-1\insurance_data.csv")
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

Splitting into training and testing data

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [4]:
X_train

    age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1
19   18              1
25   54              1
16   25              0
20   21              1
3    52              0
7    60              0
1    25              0
5    56              1
27   46              1
8    62              1
18   19              0
12   27              0
23   45              1
22   40              1
15   55              1
26   23              1
4    46              1

Data scaling

In [5]:
X_train_scaled= X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

Making the Neural Network using Tensorflow

In [6]:
model= keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,), activation='sigmoid', kernel_initializer='ones',bias_initializer='zeros')
])

c:\Users\PatelDharmikkumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [7]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled,y_train,epochs=5000)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 581ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 13/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7068
Epoch 14/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.7065
Epoch 15/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7061
Epoch 16/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7057
Epoch 17/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7054
Epoch 18/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7050
Epoch 19/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7046
Epoch 20/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7043
Epoch 21/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7039
Epoch 22/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 23/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7032
Epoch 24/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7028
Epoch 25/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7025
Epoch 26/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7021
Epoch 27/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7017
Epoch 28/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7014
Epoch 29/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7010
Epoch 30/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7007
Epoch 31/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7003
Epoch 32/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7000
Epoch 33/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6996
Epoch 34/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6993
Epoch 35/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6989
Epoch 36/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6986
Epoch 37/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6982
Epoch 38/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6979
Epoch 39/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6975
Epoch 40/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6972
Epoch 41/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6969
Epoch 42/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6965
Epoch 43/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6962
Epoch 44/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6958
Epoch 45/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6955
Epoch 46/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6952
Epoch 47/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6948
Epoch 48/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6945
Epoch 49/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6942
Epoch 50/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6938
Epoch 51/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6935
Epoch 52/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6932
Epoch 53/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6928
Epoch 54/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 55/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6922
Epoch 56/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6918
Epoch 57/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6915
Epoch 58/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6912
Epoch 59/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6909
Epoch 60/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6906
Epoch 61/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6902
Epoch 62/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 63/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6896
Epoch 64/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6893
Epoch 65/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6890
Epoch 66/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6886
Epoch 67/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6883
Epoch 68/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6880
Epoch 69/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6877
Epoch 70/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6874
Epoch 71/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 72/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6868
Epoch 73/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6865
Epoch 74/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6862
Epoch 75/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6859
Epoch 76/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 77/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6853
Epoch 78/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6849
Epoch 79/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6846
Epoch 80/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6843
Epoch 81/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6840
Epoch 82/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6838
Epoch 83/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6835
Epoch 84/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6832
Epoch 85/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6829
Epoch 86/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6826
Epoch 87/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6823
Epoch 88/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6820
Epoch 89/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6817
Epoch 90/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6814
Epoch 91/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6811
Epoch 92/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6808
Epoch 93/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6805
Epoch 94/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6803
Epoch 95/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6800
Epoch 96/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6797
Epoch 97/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6794
Epoch 98/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6791
Epoch 99/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6788
Epoch 100/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.6786
Epoch 101/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6783
Epoch 102/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6780
Epoch 103/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.6777
Epoch 104/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6775
Epoch 105/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6772
Epoch 106/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6769
Epoch 107/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6766
Epoch 108/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6764
Epoch 109/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6761
Epoch 110/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6758
Epoch 111/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6756
Epoch 112/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6753
Epoch 113/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6750
Epoch 114/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6748
Epoch 115/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6745
Epoch 116/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6742
Epoch 117/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6740
Epoch 118/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6737
Epoch 119/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6735
Epoch 120/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6732
Epoch 121/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6730
Epoch 122/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6727
Epoch 123/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6724
Epoch 124/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6722
Epoch 125/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6719
Epoch 126/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6717
Epoch 127/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.6714
Epoch 128/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6712
Epoch 129/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6709
Epoch 130/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6707
Epoch 131/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6704
Epoch 132/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.6702
Epoch 133/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6699
Epoch 134/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6697
Epoch 135/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6695
Epoch 136/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6692
Epoch 137/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6690
Epoch 138/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6687
Epoch 139/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6685
Epoch 140/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6683
Epoch 141/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6680
Epoch 142/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6678
Epoch 143/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6675
Epoch 144/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5000 - loss: 0.6673
Epoch 145/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6671
Epoch 146/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6668
Epoch 147/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6666
Epoch 148/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6664
Epoch 149/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6661
Epoch 150/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 0.6659
Epoch 151/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6657
Epoch 152/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.6655
Epoch 153/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6652
Epoch 154/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6650
Epoch 155/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6648
Epoch 156/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6646
Epoch 157/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6643
Epoch 158/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6641
Epoch 159/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6639
Epoch 160/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6637
Epoch 161/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6635
Epoch 162/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6632
Epoch 163/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6630
Epoch 164/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6628
Epoch 165/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6626
Epoch 166/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6624
Epoch 167/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6622
Epoch 168/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6620
Epoch 169/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6617
Epoch 170/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6615
Epoch 171/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6613
Epoch 172/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6611
Epoch 173/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6609
Epoch 174/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6607
Epoch 175/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6605
Epoch 176/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6603
Epoch 177/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6601
Epoch 178/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6599
Epoch 179/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6597
Epoch 180/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6595
Epoch 181/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6593
Epoch 182/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6591
Epoch 183/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6589
Epoch 184/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6587
Epoch 185/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6585
Epoch 186/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6583
Epoch 187/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6581
Epoch 188/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6579
Epoch 189/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6577
Epoch 190/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6575
Epoch 191/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6573
Epoch 192/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5455 - loss: 0.6571
Epoch 193/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6569
Epoch 194/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6568
Epoch 195/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6566
Epoch 196/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6564
Epoch 197/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5455 - loss: 0.6562
Epoch 198/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5455 - loss: 0.6560
Epoch 199/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6558
Epoch 200/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5455 - loss: 0.6556
Epoch 201/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6555
Epoch 202/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6553
Epoch 203/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6551
Epoch 204/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6549
Epoch 205/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6547
Epoch 206/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6545
Epoch 207/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6544
Epoch 208/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6542
Epoch 209/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6540
Epoch 210/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6538
Epoch 211/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6537
Epoch 212/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6535
Epoch 213/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6533
Epoch 214/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6531
Epoch 215/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6530
Epoch 216/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6528
Epoch 217/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5455 - loss: 0.6526
Epoch 218/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6525
Epoch 219/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6523
Epoch 220/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6521
Epoch 221/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5455 - loss: 0.6519
Epoch 222/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5455 - loss: 0.6518
Epoch 223/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6516
Epoch 224/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6515
Epoch 225/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6513
Epoch 226/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5455 - loss: 0.6511
Epoch 227/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5455 - loss: 0.6510
Epoch 228/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6508
Epoch 229/5000

In [8]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 1.0000 - loss: 0.3550

[0.35497763752937317, 1.0]

In [10]:
model.predict(X_test_scaled) #Anything is more than 0.5,the person will buy the insurance

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)

In [11]:
coef, intercept= model.get_weights() #get the weights and bias
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

Calculating the Output using the sigmoid function

In [24]:
def sigmoid(x):
    import math
    return 1/ (1 + np.exp(-x))

In [25]:
def prediction_function(age,affordibility):
    weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)

In [26]:
prediction_function(.47,1)

array([0.7054848], dtype=float32)

Creating a Gradient Descent Function using Python from scratch

In [27]:
def log_loss(y_true,y_prediction):
    epsilon= 1e-15
    y_prediction_new = [max(i,epsilon) for i in y_prediction]
    y_prediction_new = [min(i,1-epsilon) for i in y_prediction_new]
    y_prediction_new = np.array(y_prediction_new)
    return -np.mean(y_true*np.log(y_prediction_new)+(1-y_true)*np.log(1-y_prediction_new))

In [28]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [31]:
def gradient_descent(age,affordibility,y_true,epochs):
    #Will return w1,w2,bias
    w1 = w2 = 1
    bias = 0
    learning_rate= 0.5
    n=len(age)
    
    
    for i in range(epochs):
        weighted_sum=w1 * age + w2 + affordibility + bias
        y_predicted=sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true,y_predicted)

        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))
        bias_d=np.mean(y_predicted-y_true)

        w1=w1-learning_rate*w1d
        w2=w2-learning_rate*w2d
        bias = bias - learning_rate*bias_d
        
        print(f"Epoch:{i},w1:{w1},w1:{w2},bias:{bias},loss:{loss}")    

    return w1,w2,bias

In [32]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000)

Epoch:0,w1:0.9468767520411948,w1:0.9124306539072167,bias:-0.18674437612074016,loss:1.018275378338316
Epoch:1,w1:0.9003992424826611,w1:0.8328619790035016,bias:-0.35610837393092587,loss:0.9151313088294404
Epoch:2,w1:0.8611607698648571,w1:0.7623243182121827,bias:-0.5067102255893514,loss:0.8313655700781569
Epoch:3,w1:0.8293504287323638,w1:0.7013936907883399,bias:-0.6382200255426729,loss:0.7660995888503931
Epoch:4,w1:0.8047481556654444,w1:0.6501109849169785,bias:-0.7513391587448974,loss:0.7171711077184072
Epoch:5,w1:0.786806749391703,w1:0.6080248362899263,bias:-0.8475677107984416,loss:0.681674754165525
Epoch:6,w1:0.7747771952217023,w1:0.5743242735490958,bias:-0.9288771489254919,loss:0.6565639106999182
Epoch:7,w1:0.7678307826101037,w1:0.5480002388519579,bias:-0.9974037061572257,loss:0.6390946393221831
Epoch:8,w1:0.7651509022988786,w1:0.5279865960766613,bias:-1.0552248823146255,loss:0.627039684763143
Epoch:9,w1:0.7659886741843248,w1:0.5132586726102851,bias:-1.104228562675286,loss:0.61871826608028
Epoch:10,w1:0.7696888427420008,w1:0.5028893581883461,bias:-1.1460556954207297,loss:0.6129248742325588
Epoch:11,w1:0.7756958179183929,w1:0.4960728951723954,bias:-1.1820907756830126,loss:0.6088244758372864
Epoch:12,w1:0.7835484619131762,w1:0.4921279652634464,bias:-1.2134786346984523,loss:0.6058518930357972
Epoch:13,w1:0.7928695945475726,w1:0.4904893505887851,bias:-1.2411529935379044,loss:0.6036301358049311
Epoch:14,w1:0.803353822570098,w1:0.490694400520837,bias:-1.2658682059122084,loss:0.6019098060209157
Epoch:15,w1:0.814755629144312,w1:0.49236802601668217,bias:-1.2882297065583082,loss:0.6005264787779697
Epoch:16,w1:0.8268786268423218,w1:0.4952082209405063,bias:-1.3087211611790897,loss:0.5993717125468463
Epoch:17,w1:0.839566293599576,w1:0.49897304585316465,bias:-1.3277276869176708,loss:0.5983737422492665
Epoch:18,w1:0.85269420740807,w1:0.5034694014759366,bias:-1.3455552087631804,loss:0.5974847887887011
Epoch:19,w1:0.8661636537968713,w1:0.5085435965788623,bias:-1.3624463295635953,loss:0.5966727809068412
Epoch:20,w1:0.8798964266388763,w1:0.5140735607657734,bias:-1.3785931982803765,loss:0.5959159746987898
Epoch:21,w1:0.8938306345309188,w1:0.5199624923250558,bias:-1.3941478653411736,loss:0.5951994582711797
Epoch:22,w1:0.9079173379759918,w1:0.5261337207159428,bias:-1.4092305716420672,loss:0.5945128764184299
Epoch:23,w1:0.9221178640399399,w1:0.5325265769740116,bias:-1.4239363584577378,loss:0.5938489431841448
Epoch:24,w1:0.9364016685125665,w1:0.5390930892875518,bias:-1.4383403239845225,loss:0.5932024634151293
Epoch:25,w1:0.9507446377513951,w1:0.5457953477458007,bias:-1.4525017952497896,loss:0.5925696839474913
Epoch:26,w1:0.9651277420235309,w1:0.5526034080523842,bias:-1.4664676342903389,loss:0.5919478592011086
Epoch:27,w1:0.9795359689206868,w1:0.5594936271607367,bias:-1.4802748553619343,loss:0.5913349570931333
Epoch:28,w1:0.993957479391945,w1:0.5664473437594172,bias:-1.4939526950414335,loss:0.5907294575021493
Epoch:29,w1:1.0083829404033273,w1:0.573449833317652,bias:-1.5075242485738685,loss:0.5901302123503308
Epoch:30,w1:1.0228049975426075,w1:0.5804894812646906,bias:-1.521007762747294,loss:0.5895363471534517
Epoch:31,w1:1.0372178583908416,w1:0.5875571291928869,bias:-1.5344176570338548,loss:0.5889471908135818
Epoch:32,w1:1.0516169634968322,w1:0.5946455581334238,bias:-1.547765329899667,loss:0.5883622248958846
Epoch:33,w1:1.0659987265933855,w1:0.601749080320564,bias:-1.5610597953585013,loss:0.587781046528301
Epoch:34,w1:1.0803603295177975,w1:0.6088632167585767,bias:-1.57430818543928,loss:0.5872033409559442
Epoch:35,w1:1.094699560336407,w1:0.6159844426114843,bias:-1.587516146773317,loss:0.5866288610295138
Epoch:36,w1:1.109014685581885,w1:0.6231099861806416,bias:-1.6006881535921456,loss:0.5860574117374179
Epoch:37,w1:1.1233043494198705,w1:0.6302376702092198,bias:-1.6138277547444448,loss:0.5854888384502348
Epoch:38,w1:1.1375674940712739,w1:0.6373657866109343,bias:-1.6269377686371993,loss:0.5849230179271031
Epoch:39,w1:1.151803297010302,w1:0.6444929975881246,bias:-1.6400204370790106,loss:0.5843598513966382
Epoch:40,w1:1.166011121401595,w1:0.651618257582232,bias:-1.65307754669091,loss:0.5837992592090971
Epoch:41,w1:1.180190476985021,w1:0.6587407516683793,bias:-1.6661105247236867,loss:0.583241176687123
Epoch:42,w1:1.1943409892050763,w1:0.665859846929347,bias:-1.6791205146788402,loss:0.5826855508963297
Epoch:43,w1:1.2084623748463454,w1:0.6729750540738645,bias:-1.6921084359920961,loss:0.5821323381253818
Epoch:44,w1:1.2225544228031358,w1:0.6800859971403421,bias:-1.7050750311401484,loss:0.5815815019156138
Epoch:45,w1:1.2366169789007335,w1:0.6871923895821098,bias:-1.7180209028224225,loss:0.5810330115177584
Epoch:46,w1:1.2506499339140813,w1:0.6942940153893664,bias:-1.7309465433103068,loss:0.5804868406815601
Epoch:47,w1:1.2646532141098394,w1:0.7013907141865116,bias:-1.7438523576149387,loss:0.5799429667054261
Epoch:48,w1:1.2786267737799613,w1:0.7084823694672578,bias:-1.7567386817764028,loss:0.5794013696895893
Epoch:49,w1:1.2925705893470805,w1:0.7155688993064816,bias:-1.7696057973024284,loss:0.5788620319487758
Epoch:50,w1:1.3064846547105171,w1:0.7226502490271083,bias:-1.7824539425678867,loss:0.5783249375500409
Epoch:51,w1:1.3203689775715353,w1:0.7297263854102838,bias:-1.7952833218153312,loss:0.5777900719489252
Epoch:52,w1:1.3342235765315922,w1:0.7367972921238578,bias:-1.8080941122618566,loss:0.5772574217028965
Epoch:53,w1:1.3480484788007912,w1:0.7438629661126797,bias:-1.8208864697110514,loss:0.576726974245592
Epoch:54,w1:1.3618437183880603,w1:0.7509234147482481,bias:-1.8336605329847868,loss:0.5761987177089051
Epoch:55,w1:1.3756093346716498,w1:0.7579786535779052,bias:-1.8464164274232613,loss:0.5756726407827467
Epoch:56,w1:1.389345371269906,w1:0.7650287045474206,bias:-1.8591542676493946,loss:0.5751487326044803
Epoch:57,w1:1.4030518751491388,w1:0.7720735945973786,bias:-1.8718741597523596,loss:0.5746269826717337
Epoch:58,w1:1.4167288959187039,w1:0.7791133545547472,bias:-1.8845762030124475,loss:0.5741073807736345
Epoch:59,w1:1.4303764852739262,w1:0.7861480182575565,bias:-1.8972604912637359,loss:0.5735899169365668
Epoch:60,w1:1.443994696555777,w1:0.7931776218636787,bias:-1.9099271139707177,loss:0.5730745813813756
Epoch:61,w1:1.4575835844027596,w1:0.8002022033050116,bias:-1.9225761570790314,loss:0.5725613644895966
Epoch:62,w1:1.4711432044756254,w1:0.807221801856511,bias:-1.9352077036877693,loss:0.5720502567768068
Epoch:63,w1:1.4846736132396174,w1:0.8142364577959412,bias:-1.9478218345808602,loss:0.5715412488715839
Epoch:64,w1:1.4981748677921563,w1:0.8212462121352876,bias:-1.9604186286471321,loss:0.5710343314988973
Epoch:65,w1:1.5116470257264263,w1:0.8282511064087834,bias:-1.9729981632124403,loss:0.5705294954669898
Epoch:66,w1:1.5250901450233254,w1:0.8352511825056621,bias:-1.9855605143023243,loss:0.5700267316570143
Epoch:67,w1:1.5385042839658247,w1:0.8422464825382483,bias:-1.9981057568497829,loss:0.5695260310148444
Epoch:68,w1:1.551889501071038,w1:0.84923704873797,bias:-2.010633964859686,loss:0.5690273845445997
Epoch:69,w1:1.5652458550362858,w1:0.856222923373435,bias:-2.023145211538921,loss:0.5685307833035239
Epoch:70,w1:1.5785734046962197,w1:0.8632041486859415,bias:-2.0356395693994718,loss:0.568036218397931
Epoch:71,w1:1.5918722089886914,w1:0.8701807668387682,bias:-2.048117110340096,loss:0.5675436809799929
Epoch:72,w1:1.6051423269275333,w1:0.8771528198773532,bias:-2.060577905711103,loss:0.5670531622451928
Epoch:73,w1:1.6183838175808043,w1:0.8841203496980802,bias:-2.073022026365763,loss:0.5665646534303013
Epoch:74,w1:1.6315967400533573,w1:0.8910833980238676,bias:-2.0854495427011615,loss:0.5660781458117684
Epoch:75,w1:1.644781153472827,w1:0.898042006385135,bias:-2.0978605246907036,loss:0.56559363070444
Epoch:76,w1:1.6579371169783206,w1:0.9049962161050201,bias:-2.1102550419100217,loss:0.565111099460534
Epoch:77,w1:1.6710646897112509,w1:0.911946068287957,bias:-2.122633163557668,loss:0.5646305434688164
Epoch:78,w1:1.6841639308078629,w1:0.9188916038109097,bias:-2.134994958471686,loss:0.5641519541539414
Epoch:79,w1:1.6972348993931032,w1:0.9258328633167077,bias:-2.1473404951429207,loss:0.5636753229759152
Epoch:80,w1:1.7102776545755531,w1:0.9327698872090404,bias:-2.1596698417257545,loss:0.5632006414296601
Epoch:81,w1:1.7232922554432049,w1:0.9397027156487655,bias:-2.1719830660468054,loss:0.5627279010446569
Epoch:82,w1:1.736278761059907,w1:0.9466313885512546,bias:-2.184280235612016,loss:0.5622570933846499
Epoch:83,w1:1.7492372304623418,w1:0.9535559455845599,bias:-2.196561417612469,loss:0.5617882100473991
Epoch:84,w1:1.7621677226574246,w1:0.9604764261682294,bias:-2.208826678929197,loss:0.5613212426644717
Epoch:85,w1:1.77507029662004,w1:0.9673928694726341,bias:-2.221076086137196,loss:0.5608561829010633
Epoch:86,w1:1.787945011291047,w1:0.9743053144187019,bias:-2.2333097055088116,loss:0.5603930224558428
Epoch:87,w1:1.8007919255754983,w1:0.9812137996779704,bias:-2.2455276030166265,loss:0.5599317530608144
Epoch:88,w1:1.8136110983410307,w1:0.9881183636728931,bias:-2.2577298443359566,loss:0.5594723664811972
Epoch:89,w1:1.826402588416396,w1:0.995019044577345,bias:-2.2699164948470356,loss:0.559014854515312
Epoch:90,w1:1.8391664545901,w1:1.0019158803172863,bias:-2.282087619636956,loss:0.5585592089944792
Epoch:91,w1:1.851902755609137,w1:1.00880890857155,bias:-2.294243283501415,loss:0.5581054217829239
Epoch:92,w1:1.864611550177792,w1:1.0156981667727265,bias:-2.306383550946306,loss:0.5576534847776835
Epoch:93,w1:1.8772928969565086,w1:1.022583692108127,bias:-2.3185084861891943,loss:0.5572033899085226
Epoch:94,w1:1.8899468545608036,w1:1.0294655215208057,bias:-2.330618153160691,loss:0.5567551291378476
Epoch:95,w1:1.9025734815602253,w1:1.0363436917106297,bias:-2.3427126155057576,loss:0.5563086944606263
Epoch:96,w1:1.9151728364773455,w1:1.043218239135386,bias:-2.354791936584947,loss:0.5558640779043063
Epoch:97,w1:1.927744977786782,w1:1.0500892000119173,bias:-2.3668561794756,loss:0.5554212715287375
Epoch:98,w1:1.9402899639142477,w1:1.0569566103172798,bias:-2.3789054069730056,loss:0.5549802674260926
Epoch:99,w1:1.9528078532356197,w1:1.0638205057899177,bias:-2.3909396815915294,loss:0.5545410577207907
Epoch:100,w1:1.9652987040760312,w1:1.0706809219308513,bias:-2.4029590655657236,loss:0.5541036345694171
Epoch:101,w1:1.9777625747089789,w1:1.0775378940048739,bias:-2.4149636208514145,loss:0.5536679901606488
Epoch:102,w1:1.9901995233554475,w1:1.0843914570417559,bias:-2.4269534091267797,loss:0.5532341167151746
Epoch:103,w1:2.002609608183049,w1:1.0912416458374545,bias:-2.438928491793413,loss:0.552802006485618
Epoch:104,w1:2.0149928873051746,w1:1.0980884949553262,bias:-2.4508889299773786,loss:0.5523716517564587
Epoch:105,w1:2.027349418780161,w1:1.104932038727341,bias:-2.4628347845302643,loss:0.5519430448439554
Epoch:106,w1:2.0396792606104674,w1:1.111772311255298,bias:-2.474766116030222,loss:0.551516178096064
Epoch:107,w1:2.051982470741866,w1:1.118609346412041,bias:-2.4866829847830103,loss:0.5510910438923622
Epoch:108,w1:2.0642591070626404,w1:1.125443177842674,bias:-2.49858545082303,loss:0.550667634643966
Epoch:109,w1:2.076509227402797,w1:1.1322738389657734,bias:-2.5104735739143593,loss:0.5502459427934518
Epoch:110,w1:2.088732889533288,w1:1.1391013629746025,bias:-2.5223474135517865,loss:0.5498259608147753
Epoch:111,w1:2.100930151165241,w1:1.1459257828383203,bias:-2.53420702896184,loss:0.5494076812131893
Epoch:112,w1:2.113101069949202,w1:1.1527471313031898,bias:-2.546052479103818,loss:0.5489910965251634
Epoch:113,w1:2.1252457034743855,w1:1.1595654408937845,bias:-2.557883822670817,loss:0.548576199318301
Epoch:114,w1:2.1373641092679363,w1:1.1663807439141904,bias:-2.569701118090761,loss:0.5481629821912573
Epoch:115,w1:2.1494563447941997,w1:1.1731930724492063,bias:-2.5815044235274254,loss:0.5477514377736553
Epoch:116,w1:2.1615224674540006,w1:1.180002458365542,bias:-2.5932937968814653,loss:0.5473415587260033
Epoch:117,w1:2.173562534583933,w1:1.1868089333130107,bias:-2.605069295791441,loss:0.5469333377396105
Epoch:118,w1:2.185576603455659,w1:1.1936125287257215,bias:-2.616830977634841,loss:0.5465267675365024
Epoch:119,w1:2.1975647312752136,w1:1.2004132758232662,bias:-2.6285788995291086,loss:0.5461218408693364
Epoch:120,w1:2.2095269751823223,w1:1.207211205611903,bias:-2.6403131183326645,loss:0.5457185505213155
Epoch:121,w1:2.2214633922497264,w1:1.214006348885739,bias:-2.65203369064593,loss:0.545316889306104
Epoch:122,w1:2.233374039482516,w1:1.220798736227906,bias:-2.6637406728123496,loss:0.5449168500677404
Epoch:123,w1:2.2452589738174717,w1:1.2275883980117344,bias:-2.6754341209194124,loss:0.5445184256805511
Epoch:124,w1:2.2571182521224187,w1:1.2343753644019242,bias:-2.6871140907996733,loss:0.5441216090490635
Epoch:125,w1:2.268951931195583,w1:1.2411596653557109,bias:-2.6987806380317743,loss:0.5437263931079188
Epoch:126,w1:2.280760067764961,w1:1.2479413306240286,bias:-2.7104338179414618,loss:0.5433327708217843
Epoch:127,w1:2.292542718487698,w1:1.254720389752669,bias:-2.722073685602607,loss:0.5429407351852654
Epoch:128,w1:2.3042999399494706,w1:1.261496872083437,bias:-2.7337002958382235,loss:0.5425502792228171
Epoch:129,w1:2.316031788663882,w1:1.2682708067553015,bias:-2.7453137032214827,loss:0.5421613959886555
Epoch:130,w1:2.3277383210718625,w1:1.2750422227055442,bias:-2.756913962076731,loss:0.5417740785666685
Epoch:131,w1:2.33941959354108,w1:1.2818111486709027,bias:-2.768501126480504,loss:0.541388320070327
Epoch:132,w1:2.3510756623653593,w1:1.2885776131887108,bias:-2.78007525026254,loss:0.5410041136425946
Epoch:133,w1:2.3627065837641057,w1:1.2953416445980341,bias:-2.791636387006793,loss:0.540621452455838
Epoch:134,w1:2.3743124138817415,w1:1.3021032710408027,bias:-2.803184590052443,loss:0.540240329711737
Epoch:135,w1:2.3858932087871465,w1:1.308862520462939,bias:-2.814719912494907,loss:0.5398607386411934
Epoch:136,w1:2.3974490244731097,w1:1.3156194206154814,bias:-2.8262424071868475,loss:0.5394826725042408
Epoch:137,w1:2.408979916855786,w1:1.3223739990557055,bias:-2.837752126739179,loss:0.5391061245899526
Epoch:138,w1:2.4204859417741624,w1:1.3291262831482384,bias:-2.849249123522076,loss:0.538731088216352
Epoch:139,w1:2.431967154989531,w1:1.3358763000661722,bias:-2.860733449665975,loss:0.5383575567303202
Epoch:140,w1:2.4434236121849717,w1:1.3426240767921707,bias:-2.8722051570625795,loss:0.5379855235075033
Epoch:141,w1:2.4548553689648385,w1:1.3493696401195738,bias:-2.8836642973658617,loss:0.5376149819522221
Epoch:142,w1:2.4662624808542573,w1:1.3561130166534971,bias:-2.8951109219930604,loss:0.5372459254973788
Epoch:143,w1:2.47764500329863,w1:1.3628542328119269,bias:-2.906545082125682,loss:0.536878347604365
Epoch:144,w1:2.489002991663145,w1:1.3695933148268113,bias:-2.9179668287104956,loss:0.5365122417629689
Epoch:145,w1:2.5003365012322956,w1:1.3763302887451476,bias:-2.9293762124605283,loss:0.5361476014912827
Epoch:146,w1:2.5116455872094066,w1:1.383065180430065,bias:-2.9407732838560587,loss:0.5357844203356094
Epoch:147,w1:2.522930304716167,w1:1.3897980155619034,bias:-2.9521580931456084,loss:0.5354226918703702
Epoch:148,w1:2.534190708792171,w1:1.3965288196392867,bias:-2.963530690346932,loss:0.5350624096980101
Epoch:149,w1:2.545426854394465,w1:1.403257617980194,bias:-2.9748911252480044,loss:0.5347035674489057
Epoch:150,w1:2.5566387963971025,w1:1.4099844357230256,bias:-2.986239447408007,loss:0.5343461587812708
Epoch:151,w1:2.5678265895907053,w1:1.4167092978276628,bias:-2.997575706158312,loss:0.533990177381063
Epoch:152,w1:2.5789902886820335,w1:1.4234322290765267,bias:-3.0088999506034644,loss:0.5336356169618894
Epoch:153,w1:2.59012994829356,w1:1.43015325407563,bias:-3.020212229622161,loss:0.5332824712649133
Epoch:154,w1:2.601245622963052,w1:1.4368723972556268,bias:-3.0315125918682306,loss:0.5329307340587595
Epoch:155,w1:2.6123373671431627,w1:1.443589682872855,bias:-3.042801085771608,loss:0.5325803991394197
Epoch:156,w1:2.623405235201026,w1:1.4503051350103775,bias:-3.054077759539308,loss:0.5322314603301598
Epoch:157,w1:2.6344492814178597,w1:1.457018777579017,bias:-3.0653426611563983,loss:0.5318839114814234
Epoch:158,w1:2.645469559988573,w1:1.4637306343183876,bias:-3.0765958383869694,loss:0.5315377464707391
Epoch:159,w1:2.6564661250213857,w1:1.4704407287979209,bias:-3.087837338775099,loss:0.531192959202624
Epoch:160,w1:2.667439030537448,w1:1.4771490844178883,bias:-3.099067209645821,loss:0.5308495436084916
Epoch:161,w1:2.678388330470471,w1:1.4838557244104196,bias:-3.110285498106085,loss:0.530507493646554
Epoch:162,w1:2.689314078666362,w1:1.4905606718405158,bias:-3.1214922510457193,loss:0.5301668033017299
Epoch:163,w1:2.700216328882865,w1:1.4972639496070586,bias:-3.132687515138388,loss:0.5298274665855479
Epoch:164,w1:2.711095134789211,w1:1.5039655804438143,bias:-3.1438713368425475,loss:0.5294894775360525
Epoch:165,w1:2.721950549965771,w1:1.510665586920435,bias:-3.1550437624023986,loss:0.5291528302177089
Epoch:166,w1:2.732782627903716,w1:1.5173639914434538,bias:-3.1662048378488397,loss:0.528817518721308
Epoch:167,w1:2.7435914220046858,w1:1.524060816257276,bias:-3.1773546090004143,loss:0.5284835371638716
Epoch:168,w1:2.7543769855804596,w1:1.5307560834451666,bias:-3.188493121464258,loss:0.5281508796885568
Epoch:169,w1:2.7651393718526367,w1:1.537449814930232,bias:-3.199620420637041,loss:0.5278195404645624
Epoch:170,w1:2.775878633952321,w1:1.544142032476399,bias:-3.2107365517059105,loss:0.5274895136870318
Epoch:171,w1:2.786594824919811,w1:1.5508327576893872,bias:-3.22184155964943,loss:0.5271607935769597
Epoch:172,w1:2.7972879977042977,w1:1.5575220120176787,bias:-3.232935489238513,loss:0.5268333743810963
Epoch:173,w1:2.8079582051635668,w1:1.5642098167534826,bias:-3.2440183850373607,loss:0.5265072503718524
Epoch:174,w1:2.818605500063707,w1:1.570896193033695,bias:-3.255090291404389,loss:0.5261824158472038
Epoch:175,w1:2.829229935078825,w1:1.5775811618408557,bias:-3.2661512524931595,loss:0.5258588651305981
Epoch:176,w1:2.839831562790763,w1:1.5842647440040978,bias:-3.2772013122533044,loss:0.5255365925708575
Epoch:177,w1:2.8504104356888282,w1:1.5909469602000954,bias:-3.28824051443145,loss:0.525215592542085
Epoch:178,w1:2.8609666061695203,w1:1.597627830954006,bias:-3.2992689025721367,loss:0.5248958594435699
Epoch:179,w1:2.8715001265362696,w1:1.6043073766404081,bias:-3.3102865200187375,loss:0.5245773876996914
Epoch:180,w1:2.8820110489991793,w1:1.6109856174842347,bias:-3.3212934099143725,loss:0.5242601717598262
Epoch:181,w1:2.8924994256747727,w1:1.6176625735617018,bias:-3.332289615202822,loss:0.523944206098251
Epoch:182,w1:2.9029653085857463,w1:1.6243382648012334,bias:-3.3432751786294355,loss:0.52362948521405
Epoch:183,w1:2.913408749660728,w1:1.6310127109843815,bias:-3.354250142742039,loss:0.5233160036310186
Epoch:184,w1:2.923829800734042,w1:1.6376859317467412,bias:-3.3652145498918387,loss:0.5230037558975705
Epoch:185,w1:2.9342285135454755,w1:1.6443579465788618,bias:-3.3761684422343223,loss:0.5226927365866414
Epoch:186,w1:2.9446049397400538,w1:1.6510287748271542,bias:-3.387111861730158,loss:0.5223829402955963
Epoch:187,w1:2.95495913086782,w1:1.657698435694792,bias:-3.39804485014609,loss:0.5220743616461333
Epoch:188,w1:2.9652911383836185,w1:1.66436694824261,bias:-3.4089674490558313,loss:0.5217669952841913
Epoch:189,w1:2.9756010136468856,w1:1.6710343313899974,bias:-3.419879699840953,loss:0.5214608358798544
Epoch:190,w1:2.9858888079214427,w1:1.6777006039157867,bias:-3.430781643691773,loss:0.5211558781272579
Epoch:191,w1:2.9961545723752963,w1:1.6843657844591375,bias:-3.441673321608238,loss:0.5208521167444956
Epoch:192,w1:3.006398358080441,w1:1.6910298915204178,bias:-3.4525547744008076,loss:0.520549546473524
Epoch:193,w1:3.016620216012672,w1:1.6976929434620782,bias:-3.4634260426913306,loss:0.5202481620800704
Epoch:194,w1:3.0268201970513937,w1:1.704354958509524,bias:-3.474287166913921,loss:0.5199479583535372
Epoch:195,w1:3.0369983519794443,w1:1.7110159547519814,bias:-3.4851381873158305,loss:0.5196489301069112
Epoch:196,w1:3.047154731482915,w1:1.7176759501433607,bias:-3.49597914395832,loss:0.5193510721766664

(np.float64(7.08262420539592),
 np.float64(7.239226305953864),
 np.float64(-10.677482876578793))